# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Buletin Dakwah Kaffah"
email: "buletin-kaffah@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Wahai orang-orang yang beriman masuklah ke dalam Islam secara kaffah.
baseurl: ""
url: "https://buletinkaffah.netlify.com"
penerbit: "Lembaga Kajian Islam Kaffah"
alamat: "Wisma NH Lt-1, Jl. Raya Pasar Minggu Kav. 2 B-C Pancoran Jakarta Selatan 12780"
marketing: "Mursyid Aziz 08787-444-1924 (WA/SMS only)"
facebook_username: "buletinkaffah2017"
twitter_username: "bulletinkaffah"

# Opengraph
locale: "id"
logo_author: "/assets/images/icons/logo-kaffah-square.png"
image:
  width: 640
  height: 640

# Google Analytics
google_analytics: UA-116004889-3

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  sass_dir: assets/css

# Navbar
navigation:
  - title: "Buletin"
    url: "/buletin/"
  - title: "Hubungi Kami"
    url: "/hubungi-kami/"

# LazyLoad
lazyload:
  image_blank: "/assets/images/icons/logo-kaffah-arabic.svg"
  image_banner_blank: "/assets/images/icons/logo-kaffah-arabic-banner.svg"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
